//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPMediaPlayer.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_Courses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vd_Courses()
        {
            this.vd_CourseLessons = new HashSet<vd_CourseLessons>();
            this.vd_Orders = new HashSet<vd_Orders>();
            this.vd_UserCourses = new HashSet<vd_UserCourses>();
            this.vd_UserLessons = new HashSet<vd_UserLessons>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UrlName { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public int AuthorId { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public int Price { get; set; }
        public Nullable<bool> IsForBeginners { get; set; }
        public Nullable<bool> IsForIntermediate { get; set; }
        public Nullable<bool> IsForAdvanced { get; set; }
        public Nullable<bool> IsForKids { get; set; }
        public Nullable<bool> IsForAdults { get; set; }
        public Nullable<int> FullCourseId { get; set; }
        public string ForWhom { get; set; }
        public string Contents { get; set; }
        public string Info { get; set; }
        public Nullable<bool> HasTrial { get; set; }
        public Nullable<bool> IsBook { get; set; }
        public Nullable<bool> HasDownloadItem { get; set; }
        public Nullable<int> PriceDownloadItem { get; set; }
        public string PageText { get; set; }
        public Nullable<bool> IsLanguageCourse { get; set; }
        public Nullable<bool> IsWritingCourse { get; set; }
        public Nullable<bool> IsPackage { get; set; }
        public Nullable<int> ParentCourseId { get; set; }
        public Nullable<bool> HasPackages { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<int> ActivationFreq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_CourseLessons> vd_CourseLessons { get; set; }
        public virtual vd_Users vd_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Orders> vd_Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_UserCourses> vd_UserCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_UserLessons> vd_UserLessons { get; set; }
    }
}
