//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPMediaPlayer.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_Files
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vd_Files()
        {
            this.vd_Lessons = new HashSet<vd_Lessons>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Url { get; set; }
        public string Ext { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Lessons> vd_Lessons { get; set; }
    }
}
