//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPMediaPlayer.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_Log
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime LoginDT { get; set; }
        public Nullable<System.DateTime> LogoutDT { get; set; }
    
        public virtual vd_Users vd_Users { get; set; }
    }
}
