//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPMediaPlayer.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_Orders
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDateTime { get; set; }
        public string ResultResponse { get; set; }
        public decimal Sum { get; set; }
        public Nullable<int> UserCourseId { get; set; }
        public Nullable<decimal> IncSum { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public string SignatureValue { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<bool> IsTest { get; set; }
        public string EMail { get; set; }
    
        public virtual vd_Users vd_Users { get; set; }
        public virtual vd_UserCourses vd_UserCourses { get; set; }
        public virtual vd_Courses vd_Courses { get; set; }
    }
}
