//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPMediaPlayer.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_UserCourses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vd_UserCourses()
        {
            this.vd_Orders = new HashSet<vd_Orders>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
        public bool IsActivated { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual vd_Users vd_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Orders> vd_Orders { get; set; }
        public virtual vd_Courses vd_Courses { get; set; }
    }
}
