//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTTPMediaPlayer.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vd_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vd_Users()
        {
            this.vd_Lessons = new HashSet<vd_Lessons>();
            this.vd_UserCourses = new HashSet<vd_UserCourses>();
            this.vd_UserLessons = new HashSet<vd_UserLessons>();
            this.vd_Orders = new HashSet<vd_Orders>();
            this.vd_Log = new HashSet<vd_Log>();
            this.vd_ActionLog = new HashSet<vd_ActionLog>();
            this.vd_Courses = new HashSet<vd_Courses>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string UrlName { get; set; }
        public string Surname { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Email { get; set; }
        public bool IsAuthor { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public bool IsActivated { get; set; }
        public System.Guid Token { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string Phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Lessons> vd_Lessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_UserCourses> vd_UserCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_UserLessons> vd_UserLessons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Orders> vd_Orders { get; set; }
        public virtual vd_Countries vd_Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Log> vd_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_ActionLog> vd_ActionLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vd_Courses> vd_Courses { get; set; }
    }
}
